Repository digitalocean/doctl, pull requests merged in 2023-10, with the labels that each got.

#1438 Fix missing error handling
  do/serverless.go
  internal/apps/builder/cnb.go
Labels: hacktoberfest

#1450 Add app spec validate-offline (Resolves #1449)
  commands/apps.go
  integration/apps_spec_test.go
Labels: hacktoberfest-accepted

#1452 Load balancer update clarification
  commands/load_balancers.go
Labels: docs
